export enum ExpressionKind {
  Array = "array",
  ArrayElement = "arrayElement",
  ArraySpread = "arraySpread",
  Boolean = "boolean",
  Invocation = "invocation",
  InvocationSpread = "invocationSpread",
  Lambda = "lambda",
  Member = "member",
  Native = "native",
  Not = "not",
  Number = "number",
  Object = "object",
  ObjectComputedKey = "objectComputedKey",
  ObjectKey = "objectKey",
  ObjectSpread = "objectSpread",
  Reference = "reference",
  String = "string",
  Value = "value",
}
