export enum ExpressionKind {
  Array = "array",
  ArrayElement = "arrayElement",
  ArraySpread = "arraySpread",
  Binary = "binary",
  Boolean = "boolean",
  Invocation = "invocation",
  Lambda = "lambda",
  Member = "member",
  Native = "native",
  Number = "number",
  Object = "object",
  ObjectKey = "objectKey",
  ObjectSpread = "objectSpread",
  Reference = "reference",
  Special = "special",
  String = "string",
  Undefined = "undefined",
  Value = "value",
}
