export enum ExpressionKind {
  Array = "array",
  ArrayElement = "arrayElement",
  ArraySpread = "arraySpread",
  Binary = "binary",
  Invocation = "invocation",
  Lambda = "lambda",
  Member = "member",
  Native = "native",
  Object = "object",
  ObjectKey = "objectKey",
  ObjectSpread = "objectSpread",
  Reference = "reference",
  SpecialReference = "special",
  Value = "value",
}
