on:
  post:
    - kind: regexp
      file: deno.jsonc
      pattern: '(?<="version": ").*(?=",)'
    - kind: regexp
      file: VERSION
      pattern: ".+"
    - kind: regexp
      file: src/version.ts
      pattern: '(?<=export const version = ").*(?=";)'
