export enum PatternKind {
  And = "and",
  Any = "any",
  Array = "array",
  Block = "block",
  Boolean = "boolean",
  Equal = "equal",
  ErrorUntil = "error",
  Fail = "fail",
  Includes = "includes",
  Must = "must",
  Not = "not",
  Number = "number",
  Object = "object",
  Ok = "ok",
  Or = "or",
  Pipeline = "pipeline",
  Projection = "projection",
  Reference = "reference",
  RegExp = "regexp",
  Rule = "rule",
  Slice = "slice",
  Special = "special",
  String = "string",
  Then = "then",
  Variable = "variable",
}
