name: 'Copilot Setup'
description: 'Setup GitHub Copilot environment for Uffda development'
author: 'justinmchase'

inputs:
  deno-version:
    description: 'Deno version to install'
    required: false
    default: 'v2.x'

runs:
  using: 'composite'
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}
    
    - name: Cache Deno dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
        restore-keys: |
          ${{ runner.os }}-deno-
    
    - name: Verify Deno installation
      shell: bash
      run: |
        deno --version
        echo "Deno is ready for development"

branding:
  icon: 'code'
  color: 'blue'
