export enum PatternKind {
  And = "and",
  Any = "any",
  Character = "character",
  End = "end",
  Equal = "equal",
  Fail = "fail",
  Includes = "includes",
  Into = "into",
  Maybe = "maybe",
  Not = "not",
  Object = "object",
  Ok = "ok",
  Or = "or",
  Pipeline = "pipeline",
  Range = "range",
  Reference = "reference",
  RegExp = "regexp",
  Run = "run",
  Slice = "slice",
  Special = "special",
  Then = "then",
  Type = "type",
  Variable = "variable",
}
